{"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2372777.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2372777"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "The `_DummyThread` error messages are a [known issue](https://code.ros.org/trac/ros/ticket/3950) in rospy caused by an [underlying problem](http://bugs.python.org/issue14308) in Python.  They can be ignored.", "markup": "markdown", "html": "<p>The <code>_DummyThread</code> error messages are a <a data-is-external-link=\"true\" href=\"https://code.ros.org/trac/ros/ticket/3950\" rel=\"nofollow\">known issue</a> in rospy caused by an <a data-is-external-link=\"true\" href=\"http://bugs.python.org/issue14308\" rel=\"nofollow\">underlying problem</a> in Python.  They can be ignored.</p>", "type": "rendered"}, "created_on": "2012-11-13T01:16:34.678020+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": null, "type": "issue_comment", "id": 2372777}