{"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2372768.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2372768"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "(From [DRC Forum](http://forum.theroboticschallenge.org/index.php?topic=34.0))\n\nAfter the upgrade i am getting these Exceptions . Any thoughts on what could be the problem.?\nI  am using ubuntu 12.04 LTS\n\n    auto-starting new master\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[master]: started with pid [2666]\n    ROS_MASTER_URI=http://localhost:11311\n    \n    setting /run_id to 5fd87d2e-2aef-11e2-a1a8-00166f4cb957\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[rosout-1]: started with pid [2679]\n    started core service [/rosout]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[gazebo-2]: started with pid [2682]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[robot_state_publisher-3]: started with pid [2684]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[pr2_mechanism_diagnostics-4]: started with pid [2685]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[fake_joint_calibration-5]: started with pid [2686]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[tf2_buffer_server-6]: started with pid [2687]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[drc_robot_controllers_spawner-7]: started with pid [2690]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[camhand_controllers_spawner-8]: started with pid [2691]\n    [ WARN] [1352521841.976941519]: You've passed in true for auto_start for\n    the C++ action server at [/tf2_buffer_server]. You should always pass in\n    false to avoid race conditions.\n    Gazebo multi-robot simulator, version 1.2\n    Copyright (C) 2011 Nate Koenig, John Hsu, and contributors.\n    Released under the Apache 2 License.\n    http://gazebosim.org\n    \n    Gazebo multi-robot simulator, version 1.2\n    Copyright (C) 2011 Nate Koenig, John Hsu, and contributors.\n    Released under the Apache 2 License.\n    http://gazebosim.org\n    \n    Error [Transport.cc:102] Unable to get topic namespaces in [50] tries.\n    Error [Node.cc:72] No namespace found\n    Warning [parser.cc:375] Gazebo SDF has no <gazebo> element in\n    file[/usr/share/drcsim-1.0/models/drc_robot/model.sdf]\n    Warning [parser_urdf.cc:1125] urdf2gazebo: link[left_camera_optical_frame]\n    has no inertia, parent joint [left_camera_optical_frame_joint] ignored\n    .Warning [parser_urdf.cc:1129] urdf2gazebo: link[left_camera_optical_frame]\n    has no inertia, not modeled in gazebo\n    Warning [parser_urdf.cc:1125] urdf2gazebo: link[right_camera_optical_frame]\n    has no inertia, parent joint [right_camera_optical_frame_joint] ignored\n    .Warning [parser_urdf.cc:1129] urdf2gazebo:\n    link[right_camera_optical_frame] has no inertia, not modeled in gazebo\n    X Error of failed request:  BadDrawable (invalid Pixmap or Window\n    parameter)\n      Major opcode of failed request:  136 (DRI2)\n      Minor opcode of failed request:  3 (DRI2CreateDrawable)\n      Resource id in failed request:  0x3e00002\n      Serial number of failed request:  28\n      Current serial number in output stream:  30\n    Warning [parser.cc:286] parse from urdf file\n    [/usr/share/drcsim-1.0/models/drc_robot/model.sdf].\n    [gazebo-2] process has finished cleanly\n    log file:\n    /home/gpeter/.ros/log/5fd87d2e-2aef-11e2-a1a8-00166f4cb957/gazebo-2*.log", "markup": "markdown", "html": "<p>(From <a data-is-external-link=\"true\" href=\"http://forum.theroboticschallenge.org/index.php?topic=34.0\" rel=\"nofollow\">DRC Forum</a>)</p>\n<p>After the upgrade i am getting these Exceptions . Any thoughts on what could be the problem.?\nI  am using ubuntu 12.04 LTS</p>\n<div class=\"codehilite\"><pre><span></span>auto-starting new master\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[master]: started with pid [2666]\nROS_MASTER_URI=http://localhost:11311\n\nsetting /run_id to 5fd87d2e-2aef-11e2-a1a8-00166f4cb957\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[rosout-1]: started with pid [2679]\nstarted core service [/rosout]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[gazebo-2]: started with pid [2682]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[robot_state_publisher-3]: started with pid [2684]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[pr2_mechanism_diagnostics-4]: started with pid [2685]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[fake_joint_calibration-5]: started with pid [2686]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[tf2_buffer_server-6]: started with pid [2687]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[drc_robot_controllers_spawner-7]: started with pid [2690]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[camhand_controllers_spawner-8]: started with pid [2691]\n[ WARN] [1352521841.976941519]: You&#39;ve passed in true for auto_start for\nthe C++ action server at [/tf2_buffer_server]. You should always pass in\nfalse to avoid race conditions.\nGazebo multi-robot simulator, version 1.2\nCopyright (C) 2011 Nate Koenig, John Hsu, and contributors.\nReleased under the Apache 2 License.\nhttp://gazebosim.org\n\nGazebo multi-robot simulator, version 1.2\nCopyright (C) 2011 Nate Koenig, John Hsu, and contributors.\nReleased under the Apache 2 License.\nhttp://gazebosim.org\n\nError [Transport.cc:102] Unable to get topic namespaces in [50] tries.\nError [Node.cc:72] No namespace found\nWarning [parser.cc:375] Gazebo SDF has no &lt;gazebo&gt; element in\nfile[/usr/share/drcsim-1.0/models/drc_robot/model.sdf]\nWarning [parser_urdf.cc:1125] urdf2gazebo: link[left_camera_optical_frame]\nhas no inertia, parent joint [left_camera_optical_frame_joint] ignored\n.Warning [parser_urdf.cc:1129] urdf2gazebo: link[left_camera_optical_frame]\nhas no inertia, not modeled in gazebo\nWarning [parser_urdf.cc:1125] urdf2gazebo: link[right_camera_optical_frame]\nhas no inertia, parent joint [right_camera_optical_frame_joint] ignored\n.Warning [parser_urdf.cc:1129] urdf2gazebo:\nlink[right_camera_optical_frame] has no inertia, not modeled in gazebo\nX Error of failed request:  BadDrawable (invalid Pixmap or Window\nparameter)\n  Major opcode of failed request:  136 (DRI2)\n  Minor opcode of failed request:  3 (DRI2CreateDrawable)\n  Resource id in failed request:  0x3e00002\n  Serial number of failed request:  28\n  Current serial number in output stream:  30\nWarning [parser.cc:286] parse from urdf file\n[/usr/share/drcsim-1.0/models/drc_robot/model.sdf].\n[gazebo-2] process has finished cleanly\nlog file:\n/home/gpeter/.ros/log/5fd87d2e-2aef-11e2-a1a8-00166f4cb957/gazebo-2*.log\n</pre></div>", "type": "rendered"}, "created_on": "2012-11-13T01:13:39.967025+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": null, "type": "issue_comment", "id": 2372768}